### ISSUE TITLE
Typo in gravwell-file-follow ncurses screen

### ISSUE THREAD

**Issue by createchange** [gravwell/ingesters#1]
The initial window that appears says "serveral" rather than several. I tried finding the appropriate file so I could correct this, but was unable to.

Thanks for making the community version available!

**Comment by traetox** [comment]
Thank you very much.  We found and corrected the miss spelling and just pushed it as part of the 2.1.0 release.  We are in the process of cleaning up the build scripts for the ingesters and will be including them in the repo shortly.

Thank you again!
